---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  yarn: true
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g yarn bower phantomjs-prebuilt
  - yarn --version
  - bower --version
  - phantomjs --version

install:
  - yarn install
  - bower install

script:
  - npm test
